services:
  - type: web
    name: neurotrack
    env: python
    region: ohio
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
    startCommand: gunicorn server:app --timeout 300 --workers 2 --threads 4 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: MAX_CONTENT_LENGTH
        value: 524288000
    plan: standard
    autoDeploy: true
